version: 2.1

orbs:
  docker: circleci/docker@2.1.1  

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable  
    steps:
      - setup_remote_docker

      - checkout

      - docker/check  

      - docker/build:
          image: onkarko1106/circleci-demo-docker_orbs
          tag: "latest"            
      
      - docker/push:
          digest-path: /tmp/digest.txt  # Stores image digest in a file
          image: onkarko1106/circleci-demo-docker_orbs
          tag: "latest"                 # Tag to be pushed

      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"  # Prints the image digest

workflows:
  commit:
    jobs:
      - build-and-push
