# version: 2.1
# orbs:
#   docker: circleci/docker@2.7.2
# workflows:
#   build-docker-image-only:
#     jobs:
#       - docker/publish:
#           deploy: false
#           image: react_project/gitaction-org


#----------------------------------above getting build"

version: 2.1
orbs:
  docker: circleci/docker@2.7.2  # Make sure you have the correct version

workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          dockerfile: my.Dockerfile
          image: react_project/gitaction-org  # Change this to your Docker Hub username and repository name
          path: react_project/gitaction-org  # Path to your Docker build context
          registry: docker.io  # Set the registry to Docker Hub (default)
          use-docker-credentials-store: true


#------------------------------------

# version: 2.1

# jobs:
#   build:
#     docker:
#       - image: circleci/python:3.8  # Use an appropriate image for your build environment
#     steps:
#       - checkout
#       # Add other steps for your build process, if needed
#       - docker/publish:
#           dockerfile: my.Dockerfile
#           image: react_project/gitaction-org 
#           path: react_project/gitaction-org  # Path to your Docker build context

#   publish:
#     docker:
#       - image: circleci/python:3.8  # Use an appropriate image for your publish environment
#     steps:
#       - checkout
#       # Login to Docker Hub using the command line
#       - run:
#           name: Docker Login
#           command: |
#             docker login -u "onkarko1106" -p "onkarko1106" "docker.io "
#       # Publish the Docker image
#       - run:
#           name: Publish Docker Image
#           command: |
#             docker build -f my.Dockerfile -t react_project/gitaction-org react_project/gitaction-org
#             docker push react_project/gitaction-org

# workflows:
#   build-and-publish-docker-image:
#     jobs:
#       - build
#       - publish:
#           requires:
#             - build  # Ensure the build job completes before publishing
