version: 2.1

orbs:
  docker: circleci/docker@2.7.2

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - docker/build:
          image: onkarko1106/circleci-demo-docker
          tag: "0.2"

      - docker/push:
          image: onkarko1106/circleci-demo-docker
          tag: "0.2"
          username: "onkarko1106"
          password: "onkarko1106"
