# version: 2.1
# orbs:
#   docker: circleci/docker@2.7.2
# workflows:
#   build-and-publish-docker-image:
#     jobs:
#       - docker/publish:
#           image: onkarko1106/mycircleciimage_orbs
#           use-docker-credentials-store: true



version: 2.1
orbs:
  docker: circleci/docker@2.7.2
workflows:
  build-and-publish-docker-image:
    jobs:
      - docker/publish:
          image: onkarko1106/mycircleciimage_orbs
          registry: docker.io
          username: $DOCKER_USER
          password: $DOCKER_PASS
