# version: 2.1
# orbs:
#   docker: circleci/docker@2.7.2
# workflows:
#   build-docker-image-only:
#     jobs:
#       - docker/publish:
#           deploy: false
#           image: react_project/gitaction-org


#----------------------------------above getting build"

# version: 2.1
# orbs:
#   docker: circleci/docker@2.7.2  # Make sure you have the correct version

# workflows:
#   build-and-publish-docker-image:
#     jobs:
#       - docker/publish:
#           dockerfile: my.Dockerfile
#           image: react_project/gitaction-org  # Change this to your Docker Hub username and repository name
#           path: react_project/gitaction-org  # Path to your Docker build context
#           registry: docker.io  # Set the registry to Docker Hub (default)


#------------------------------------

version: 2.1

orbs:
  docker: circleci/docker@2.7.2
  # Add the docker login orb
  login: circleci/docker@2.7.2 

jobs:
  build:
    docker:
      - image: circleci/python:3.8  # Use an appropriate image for your build environment
    steps:
      - checkout
      # Add other steps for your build process, if needed
      - docker/build:
          dockerfile: my.Dockerfile
          image: react_project/gitaction-org 
          path: react_project/gitaction-org  # Path to your Docker build context

  publish:
    docker:
      - image: circleci/python:3.8  # Use an appropriate image for your publish environment
    steps:
      - checkout
      # Login to Docker Hub
      - login/docker:
          username: "onkarko1106"  # Ensure this is set in your CircleCI project settings
          password: "onkarko1106"  # Ensure this is set in your CircleCI project settings
      # Publish the Docker image
      - docker/publish:
          dockerfile: my.Dockerfile
          image: react_project/gitaction-org  # Change this to your Docker Hub username and repository name
          path: react_project/gitaction-org  # Path to your Docker build context
          registry: docker.io  # Set the registry to Docker Hub (default)

workflows:
  build-and-publish-docker-image:
    jobs:
      - build
      - publish:
          requires:
            - build  # Ensure the build job completes before publishing
