version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          TAG=0.2
          docker build -t onkarko1106/circleci-demo-docker:$TAG .
          echo "onkarko1106" | docker login -u "onkarko1106" --password-stdin
          docker push onkarko1106/circleci-demo-docker:$TAG